services:
  app:
  # set container name
    container_name: turva-backend

  # build image from dockerfile in the current directory
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
        restart: true

    # map container port to host 
    ports:
      - "3000:3000"
    env_file:
      - ".env"

  postgres:
    image: postgres:latest
    container_name: turva-database
    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 1s
      retries: 5
      timeout: 5s

    # use example.sql to create a database with example data
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

    # store `POSTGRES_PASSWORD` in .env
    env_file: 
    - ".env"
    
